import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css"
import Header from "./Components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:mx-10 md:px-20 px-5 py-5 `}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
